on:
  push:
name: Publish
jobs:
  publish:
    name: Publish
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Cache Common
        uses: actions/cache@v3
        with:
          path: common
          key: ${{ runner.os }}-common-${{ hashFiles('common/**', 'build.gradle.kts', 'gradle.properties', 'gradle/libs.versions.toml') }}

      - name: Cache Common-Compose
        uses: actions/cache@v3
        with:
          path: common-compose
          key: ${{ runner.os }}-common-compose-${{ hashFiles('common-compose/**', 'build.gradle.kts', 'gradle.properties', 'gradle/libs.versions.toml') }}

      - name: Setup Android SDK
        if: matrix.os == 'ubuntu-latest'
        uses: android-actions/setup-android@v3

      - name: Build
        run: |
          ./gradlew build

      - name: Publish
        run: |
          ./gradlew publish
        env:
          REPOSILITE_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}

      - name: Stop Daemon
        run: |
          ./gradlew --stop

      - name: Clean up windows
        if: matrix.os == 'windows-latest'
        run: |
          Remove-Item -Path appDesktop/build/compose/binaries -Recurse -Force

      - name: Clean up linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          rm -rf appDesktop/build/compose/binaries
          rm -rf appAndroid/build/outputs