on:
  push:
name: Publish
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Cache Common
        uses: actions/cache@v3
        with:
          path: common
          key: common-${{ hashFiles('common/**', 'build.gradle.kts', 'gradle.properties', 'gradle/libs.versions.toml') }}

      - name: Cache Common-Compose
        uses: actions/cache@v3
        with:
          path: common-compose
          key: common-compose-${{ hashFiles('common-compose/**', 'build.gradle.kts', 'gradle.properties', 'gradle/libs.versions.toml') }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Publish
        run: |
          ./gradlew --no-daemon publish
        env:
          REPOSILITE_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}
          EventName: ${{ github.event_name }}